import { create } from 'zustand'

export type Language = 'ar' | 'fr'

const frDictionary: Record<string, string> = {
  // Navigation & Core App Headers
  'MELLAH POS': 'MELLAH POS',
  'الفرع الرئيسي': 'Succursale Principale',
  'أونلاين (متزامن)': 'En ligne (Synchronisé)',
  'أوفلاين (محلي)': 'Hors ligne (Local)',
  'إعادة الاتصال': 'Se reconnecter',
  'جاري الفحص...': 'Vérification...',
  'مدير النظام': 'Administrateur',
  'مشرف المتجر': 'Superviseur',
  'كاشير': 'Caissier',
  'خروج': 'Déconnexion',
  'لوحة التحكم والتشغيل المركزية': 'Tableau de Bord Principal',
  'مرحباً بك،': 'Bienvenue,',
  'اختر الوحدة المطلوبة للبدء. نظام نقاط البيع يعمل بمرونة وسرعة تامة.': 'Sélectionnez un module pour commencer. Le système fonctionne en toute sécurité.',
  'الفرع النشط': 'Magasin Actif',
  'وضع التشغيل': 'Mode de Fonctionnement',
  'محلي فائق السرعة + متزامن': 'Local Ultra Rapide + Synchro',
  'صلاحياتك الحالية': 'Vos Autorisations',
  'وحدات النظام المتوفرة': 'Modules Disponibles',
  'متاحة حسب صلاحياتك': 'disponibles selon vos droits',
  'إغلاق النافذة': 'Fermer la fenêtre',
  'نافذة جديدة': 'Nouvelle fenêtre',
  'شاشة رئيسية': 'Écran principal',
  'الرئيسية': 'Accueil',
  'شاشة نقطة البيع (POS)': 'Écran Caisse (POS)',
  'وردية نشطة': 'Caisse Active',
  'ورديّة نشطة': 'Caisse Active',
  'مغلقة': 'Fermée',
  'فتح الدرج': 'Ouvrir Tiroir',
  'إغلاق الوردية': 'Clôturer Caisse',
  'إغلاق وردية': 'Clôturer Caisse',
  'السلال المعلقة': 'Ventes en Attente',
  'فرع الجزائر العاصمة': 'Succursale Alger',
  'مبيعات اليوم': 'Ventes du Jour',
  'عملية': 'opérations',

  // Launcher Tiles
  'نقطة البيع (POS)': 'Caisse (POS)',
  'واجهة الكاشير البيع الفوري السريع': 'Interface de Vente Rapide',
  'سجل المبيعات': 'Historique des Ventes',
  'استعراض الفواتير وإعادة الطباعة': 'Consulter les factures et réimprimer',
  'إدارة المرتجعات': 'Gestion des Retours',
  'استرجاع المنتجات والتعويضات': 'Retours de produits et avoirs',
  'الزبائن والولاء': 'Clients & Fidélité',
  'قاعدة الزبائن ونقاط المكافآت': 'Base clients et points de fidélité',
  'طباعة الملصقات': 'Imprimer des Étiquettes',
  'تيكيتات الباركود 40mm×30mm': 'Étiquettes Code-barres 40x30mm',
  'المنتجات والمخزون': 'Produits & Stock',
  'إضافة السلع والمقاسات والألوان': 'Gestion des produits, tailles & couleurs',
  'التقارير والتحليلات': 'Rapports & Analyses',
  'مؤشرات الأرباح والمبيعات الحية': 'Statistiques de ventes et bénéfices',
  'إدارة المستخدمين': 'Gestion des Utilisateurs',
  'إضافة وحذف وتعيين أدوار الطاقم': 'Gestion du personnel et privilèges',
  'إدارة الفروع': 'Gestion des Succursales',
  'الفروع والمحلات التابعة للمتجر': 'Points de vente et magasins',
  'إعدادات المتجر': 'Paramètres du Magasin',
  'بيانات الفاتورة والنسخ الاحتياطي': 'Informations du ticket et sauvegarde',
  'سجل العمليات (Audit)': 'Journal d\'Audit',
  'استعراض سجل التدقيق والأمان': 'Historique des actions et sécurité',
  'الصيانة والتحديثات': 'Maintenance & Mises à jour',
  'فحص وإصلاح النظام وتحديث التطبيق': 'Vérification, réparation et mises à jour',
  'أدوات الفحص والإصلاح وتحديث النظام': 'Outils d\'inspection, de réparation et mise à jour',
  'صيانة شاملة': 'Maintenance Complète',
  'جاري الصيانة الشاملة...': 'Maintenance en cours...',
  'إصدار التطبيق': 'Version de l\'application',
  'حجم قاعدة البيانات': 'Taille de la base de données',
  'حالة النظام': 'État du système',
  'يعمل بشكل طبيعي': 'Fonctionne normalement',
  'أدوات الصيانة والإصلاح': 'Outils de maintenance et réparation',
  'فحص سلامة قاعدة البيانات': 'Vérification d\'intégrité de la base',
  'يتحقق من عدم وجود تلف أو بيانات معطوبة في قاعدة البيانات المحلية.': 'Vérifie l\'absence de corruption dans la base de données locale.',
  'ضغط وتحسين قاعدة البيانات': 'Compacter et optimiser la base',
  'يُعيد تنظيم ملف القاعدة ويحرر المساحة غير المستخدمة لتسريع الأداء.': 'Réorganise le fichier et libère l\'espace inutilisé.',
  'تنظيف الملفات المؤقتة والكاش': 'Nettoyer le cache et fichiers temporaires',
  'يحذف ملفات الكاش المؤقتة التي قد تسبب بطء أو مشاكل في العرض.': 'Supprime les fichiers temporaires pouvant ralentir l\'affichage.',
  'تشغيل': 'Exécuter',
  'التحديثات': 'Mises à jour',
  'فحص التحديثات': 'Vérifier les mises à jour',
  'تحديث جديد متوفر': 'Nouvelle mise à jour disponible',
  'يتوفر إصدار جديد من Mellah POS. حمّله الآن لتحسين الأداء والأمان.': 'Une nouvelle version de Mellah POS est disponible.',
  'جاري تحميل التحديث...': 'Téléchargement de la mise à jour...',
  'التحديث جاهز للتثبيت': 'Mise à jour prête à être installée',
  'اضغط على الزر لإعادة التشغيل وتثبيت التحديث.': 'Cliquez pour redémarrer et installer la mise à jour.',
  'تحميل التحديث': 'Télécharger la mise à jour',
  'إعادة التشغيل والتثبيت': 'Redémarrer et Installer',
  'أنت تستخدم أحدث إصدار ✅': 'Vous utilisez la dernière version ✅',
  'تمت الصيانة الشاملة بنجاح ✅': 'Maintenance complète réussie ✅',
  'انتهت الصيانة مع بعض التحذيرات ⚠️': 'Maintenance terminée avec des avertissements ⚠️',

  // POS Checkout Page
  'مبلغ الباقي للزبون': 'Rendu Monnaie Client',
  'مبلغ الباقي للزبون:': 'Rendu Monnaie Client:',
  'تعليق الفاتورة (F2)': 'Mettre en Attente (F2)',
  'فتح درج النقد': 'Ouvrir Tiroir-Caisse',
  'بحث باسم المنتج أو الباركود...': 'Rechercher produit ou code-barres...',
  'ابحث باسم المنتج، اللون، المقاس، أو امسح الباركود...': 'Rechercher par nom, couleur, taille ou code-barres...',
  'السلة الحالية': 'Panier Actuel',
  'سلة البيع الحالية': 'Panier de Vente Actuel',
  'تفاصيل الدفع': 'Détails du Paiement',
  'نقداً (كاش)': 'Espèces (Cash)',
  'بطاقة CIB': 'Carte CIB',
  'دفع مختلط (كاش + CIB)': 'Paiement Mixte',
  'رصيد المتجر': 'Avoir Magasin',
  'استبدال نقاط الولاء': 'Échanger Points de Fidélité',
  'تحديد الزبون': 'Sélectionner un Client',
  '— اختر زبون لجمع نقاط الولاء —': '— Sélectionner un client pour accumuler les points —',
  'زبون عادي (افتراضي)': 'Client Standard',
  'إضافة زبون جديد': 'Nouveau Client',
  'إتمام عملية البيع (Enter)': 'Valider la Vente (Enter)',
  'إتمام عملية البيع': 'Valider la Vente',
  'جاري معالجة البيع...': 'Traitement de la vente...',
  'الخصم (دج):': 'Remise (DZD):',
  'الخصم (دج)': 'Remise (DZD)',
  'الخصم المطبق:': 'Remise appliquée:',
  'المجموع الفرعي:': 'Sous-total:',
  'المجموع الفرعي': 'Sous-total',
  'المبلغ النهائي:': 'Montant Total:',
  'المبلغ النهائي المستحق:': 'Net à Payer:',
  'المبلغ النهائي المستحق': 'Net à Payer',
  'المبلغ المدفوع كاش:': 'Montant Espèces:',
  'المبلغ النقدي المقدم من الزبون:': 'Espèces reçues du client:',
  'الباقي للزبون (Change):': 'Monnaie à rendre (Rendu):',
  'السلة فارغة حالياً': 'Le panier est actuellement vide',
  'أضف منتجات من القائمة أو امسح الباركود للبدء': 'Ajoutez des produits de la liste ou scannez un code-barres',
  'انقر على أي منتج لإضافته للطلب': 'Cliquez sur un produit pour l\'ajouter',
  'حاسبة الباقي': 'Calculateur de Monnaie',
  'الباقي المستحق للزبون:': 'Monnaie à rendre au client:',
  'تأكيد الدفع وإتمام البيع': 'Valider le paiement',
  'إلغاء': 'Annuler',
  '💵 نقد': '💵 Espèces',
  '💳 CIB': '💳 CIB',
  '🔀 مزدوج': '🔀 Mixte',
  'نقداً': 'Espèces',
  'مزدوج': 'Mixte',
  'استبدال': 'Échanger',
  'تطبيق رصيد المتجر': 'Appliquer avoir magasin',

  // Categories & Colors
  'جميع الفئات': 'Toutes les Catégories',
  'أحذية': 'Chaussures',
  'إكسسوارات': 'Accessoires',
  'ملابس رجالية': 'Vêtements Homme',
  'ملابس نسائية': 'Vêtements Femme',
  'عام': 'Général',
  'لا توجد منتجات تطابق البحث': 'Aucun produit ne correspond à la recherche',
  'تأكد من اختيار الفئة أو كلمة البحث': 'Vérifiez la catégorie ou le terme de recherche',
  'أسود': 'Noir',
  'أبيض': 'Blanc',
  'أزرق': 'Bleu',
  'أحمر': 'Rouge',
  'أخضر': 'Vert',
  'رمادي': 'Gris',
  'وردي': 'Rose',
  'بني': 'Marron',
  'أصفر': 'Jaune',
  'برتقالي': 'Orange',
  'كحلي': 'Bleu Marine',
  'بيج': 'Beige',
  'قطعة': 'pcs',
  'قطع': 'pcs',
  'مقاس:': 'Taille:',
  'لون:': 'Couleur:',
  'الستوك:': 'Stock:',
  'نفد': 'Épuisé',

  // Products & Inventory Page
  'إضافة منتج جديد': 'Ajouter un Produit',
  'إدارة المنتجات والمخزون': 'Gestion des Produits et du Stock',
  'استيراد CSV': 'Importer CSV',
  'تعديل الأسعار جماعياً': 'Modification Prix en Masse',
  'تصدير CSV': 'Exporter CSV',
  'طلب تزود (PO)': 'Bon de Commande (PO)',
  'الفئات': 'Catégories',
  'المنخفض فقط': 'Stock Bas Uniquement',
  'ابحث باسم المنتج أو الفئة...': 'Rechercher par nom ou catégorie...',
  'المنتج': 'Produit',
  'السعر الافتراضي': 'Prix Par Défaut',
  'عدد الخيارات': 'Nombre de Variantes',
  'إجمالي المخزون (Ledger)': 'Stock Total (Ledger)',
  'الإجراءات': 'Actions',
  'التفاصيل والجرد': 'Détails & Stock',
  'لا توجد منتجات مسجلة طابق البحث': 'Aucun produit ne correspond à la recherche',
  'التعديل الجماعي لأسعار البيع (Bulk Price Update)': 'Modification de Prix en Masse',
  'اختر الفئة المستهدفة:': 'Sélectionner la catégorie ciblée:',
  'نوع التعديل:': 'Type de modification:',
  'نسبة مئوية (%)': 'Pourcentage (%)',
  'مبلغ ثابت (دج DZD)': 'Montant Fixe (DZD)',
  'قيمة التعديل (+ للزيادة، - للتخفيض):': 'Valeur (+ augmentation, - réduction):',
  'تأكيد وتطبيق التعديل الجماعي': 'Confirmer et appliquer',
  'جميع الفئات والمنتجات': 'Toutes les catégories et produits',

  // Product Detail Page
  'تفاصيل المنتج والجرد': 'Détails du Produit et Stock',
  'تعديل بيانات المنتج': 'Modifier le Produit',
  'حذف المنتج': 'Supprimer le Produit',
  'إضافة خيار جديد (مقاس/لون)': 'Ajouter une Variante (Taille/Couleur)',
  'حركات المخزون (Stock Movement History)': 'Historique des Mouvements de Stock',
  'اسم المنتج:': 'Nom du Produit:',
  'الفئة:': 'Catégorie:',
  'سعر البيع:': 'Prix de Vente:',
  'التكلفة:': 'Coût d\'Achat:',
  'الوصف:': 'Description:',
  'المقاس': 'Taille',
  'اللون': 'Couleur',
  'الباركود': 'Code-barres',
  'رمز SKU': 'Code SKU',
  'المخزون الحالي': 'Stock Actuel',
  'الحد الأدنى للمخزون': 'Stock Minimum',
  'تعديل الستوك': 'Ajuster le Stock',
  'نوع الحركة': 'Type de mouvement',
  'تزويد (Restock)': 'Réapprovisionnement',
  'تعديل (Adjustment)': 'Ajustement',
  'تالف (Damaged)': 'Endommagé',
  'حفظ التعديلات': 'Enregistrer les modifications',
  'قطعة بالمخزون': 'pcs en stock',

  // Sales History Page & Modal
  'سجل المبيعات والتنزيلات': 'Historique des Ventes',
  'سجل الفواتير والمبيعات اليومية': 'Historique des Factures & Ventes',
  'العودة للشاشة الرئيسية': 'Retour à l\'Accueil',
  'تصدير السجلات CSV': 'Exporter CSV',
  'إجمالي الفواتير النشطة': 'Total Factures Actives',
  'مجموع المبيعات المحددة': 'Total des Ventes',
  'إجمالي المبيعات المحُددة': 'Total des Ventes Sélectionnées',
  'فواتير ملغاة': 'Factures Annulées',
  'الوردية الحالية': 'Session Caisse Actuelle',
  'مجال تاريخ (من-إلى)': 'Période (Du-Au)',
  'ابحث برقم الفاتورة أو اسم الكاشير...': 'Rechercher par n° de facture ou caissier...',
  'فلترة بالتواريخ': 'Filtrer par Date',
  'كل الأوقات': 'Tout le temps',
  'اليوم': 'Aujourd\'hui',
  'أمس': 'Hier',
  'آخر 7 أيام': '7 derniers jours',
  'آخر 30 يوم': '30 derniers jours',
  'مخصص': 'Personnalisé',
  'رقم الفاتورة': 'N° Facture',
  'التاريخ والوقت': 'Date & Heure',
  'الكاشير': 'Caissier',
  'الزبون': 'Client',
  'الكاشير والزبون': 'Caissier & Client',
  'المبلغ الإجمالي': 'Montant Total',
  'مبلغ الفاتورة': 'Montant Facture',
  'طريقة الدفع': 'Mode de Paiement',
  'الحالة': 'Statut',
  'مكتملة': 'Complétée',
  'ملغاة (Voided)': 'Annulée (Voided)',
  'مرتجعة': 'Retournée',
  'إعادة طباعة': 'Réimprimer',
  'إلغاء الفاتورة (Void)': 'Annuler la Facture (Void)',
  'تفاصيل الفاتورة': 'Détails de la Facture',
  'التفاصيل والطباعة': 'Détails & Impression',
  'لا توجد مبيعات مسجلة في هذا التاريخ': 'Aucune vente enregistrée à cette date',

  // Returns Page
  'إدارة المرتجعات واستبدال البضاعة': 'Gestion des Retours Produit',
  'ابحث برقم الوصل أو رقم الفاتورة...': 'Rechercher par n° de ticket ou facture...',
  'تفاصيل الفاتورة الأصلية': 'Détails de la Facture Origine',
  'تحديد المواد المراد إرجاعها': 'Sélectionner les articles à retourner',
  'الكمية المرتجعة': 'Quantité Retournée',
  'سبب الإرجاع': 'Motif du retour',
  'طريقة التعويض': 'Mode de Remboursement',
  'إرجاع نقداً (كاش)': 'Remboursement Espèces',
  'رصيد متجر (Store Credit)': 'Avoir Magasin (Store Credit)',
  'تأكيد تسجيل المرتجع': 'Valider le Retour',
  'طباعة وصل المرتجع': 'Imprimer le Ticket de Retour',

  // Customers Page
  'إدارة الزبائن وعضوية الولاء': 'Gestion des Clients & Fidélité',
  'اسم الزبون': 'Nom du Client',
  'رقم الهاتف': 'Téléphone',
  'نقاط الولاء': 'Points de Fidélité',
  'سجل المشتريات': 'Historique des Achats',
  'تعديل': 'Modifier',
  'حذف': 'Supprimer',
  'تعديل بيانات الزبون': 'Modifier le Client',

  // Reports Page
  'التقارير المالية والتحليلات': 'Rapports Financiers & Analyses',
  'إجمالي المبيعات': 'Ventes Totales',
  'صافي الأرباح': 'Bénéfice Net',
  'تكلفة البضاعة المباعة (COGS)': 'Coût des Marchandises (COGS)',
  'إجمالي الفواتير': 'Total des Factures',
  'هامش الربح': 'Marge Bénéficiaire',
  'أفضل 10 منتجات مبيعاً': 'Top 10 des Produits',
  'توزيع طرق الدفع': 'Répartition des Paiements',
  'سجل الورديات': 'Historique des Caisses',
  'تصدير التقارير': 'Exporter les Rapports',

  // Users & Roles Page
  'إدارة المستخدمين والأدوار': 'Gestion des Utilisateurs',
  'إضافة مستخدم جديد': 'Nouveau Utilisateur',
  'الاسم الكامل': 'Nom Complet',
  'الدور / الصلاحية': 'Rôle / Permissions',
  'رمز PIN (4 أرقام)': 'Code PIN (4 chiffres)',
  'تعديل البيانات': 'Modifier les Infos',
  'تغيير رمز PIN': 'Changer le PIN',
  'حذف المستخدم': 'Supprimer l\'utilisateur',

  // Branches Page
  'إدارة الفروع والمحلات': 'Gestion des Succursales',
  'إضافة فرع جديد': 'Nouvelle Succursale',
  'اسم الفرع': 'Nom de la Succursale',
  'العنوان': 'Adresse',

  // Audit Log Page
  'سجل التغييرات والعمليات (Audit Log Viewer)': 'Journal d\'Audit et Sécurité',
  'ابحث بالاسم، التفاصيل، أو العملية...': 'Rechercher par nom, détails ou action...',
  'المستخدم / المنفذ': 'Utilisateur / Opérateur',
  'نوع العملية (Action)': 'Type d\'Action',
  'القسم / النطاق': 'Domaine',
  'تفاصيل العملية والتغييرات': 'Détails de l\'action',

  // Label Printer Page
  'طباعة بطاقات الأسعار والباركود للملابس (Price Tags)': 'Impression d\'Étiquettes & Codes-barres',
  'اختر المنتج لطباعة تيكيتات مقاساته وألوانه:': 'Sélectionnez un produit pour imprimer ses étiquettes:',
  'طباعة الكل': 'Tout Imprimer',
  'معاينة نموذج البطاقة الحرارية (40mm × 30mm)': 'Aperçu de l\'étiquette thermique (40x30mm)',
  'العدد:': 'Quantité:',

  // Settings Page
  'إعدادات المتجر وطابعة الفواتير واللغة والنسخ الاحتياطي': 'Paramètres du Magasin, Imprimante & Langue',
  'بيانات المتجر والفواتير': 'Information du Magasin & Tickets',
  'اسم المتجر (المطبوع أعلى الفاتورة)': 'Nom du Magasin (en haut du ticket)',
  'عنوان المتجر': 'Adresse du Magasin',
  'هاتف المتجر': 'Téléphone du Magasin',
  'نص أسفل الفاتورة الحرارية (Footer Text)': 'Pied de page du ticket (Footer)',
  'اللغة والأمان': 'Langue & Sécurité',
  'لغة الواجهة (Language)': 'Langue de l\'interface',
  'قفل الجلسة عند التوقف (دقائق)': 'Délai de verrouillage (min)',
  'إعدادات طابعة الفواتير الحرارية (Thermal Printer)': 'Paramètres de l\'imprimante thermique',
  'طابعة الفواتير المتصلة بالكمبيوتر': 'Imprimante connectée au PC',
  'عرض ورق الفواتير الحرارية': 'Largeur du papier thermique',
  'طباعة تجريبية': 'Test d\'impression',
  'طباعة فاتورة تجريبية': 'Imprimer un ticket test',
  'حفظ الإعدادات': 'Enregistrer les paramètres',
  'النسخ الاحتياطي واسترجاع البيانات': 'Sauvegarde & Restauration',
  'تصدير نسخة احتياطية (Backup)': 'Exporter une sauvegarde (Backup)',
  'حفظ ملف JSON محلي يحتوي على كل بيانات المتجر والمبيعات والمنتجات.': 'Télécharger un fichier JSON contenant toutes les données du magasin.',
  'تصدير ملف النسخة الاحتياطية': 'Télécharger la sauvegarde',
  'استرجاع نسخة احتياطية (Restore)': 'Restaurer une sauvegarde (Restore)',
  'حول برنامج Mellah POS': 'À propos de Mellah POS',
  'إصدار النظام:': 'Version du Système:',
  'قاعدة البيانات:': 'Base de Données:',
  'محرك الواجهة:': 'Moteur d\'Interface:',

  // Login Page & Modals
  'تسجيل الدخول للنظام': 'Connexion au Système',
  'رمز PIN الخصي بك (4 أرقام)': 'Code PIN (4 chiffres)',
  'دخول': 'Connexion',

  // System Restart & Shift Modals
  'تأكيد إعادة تشغيل التطبيق': 'Confirmer le redémarrage',
  'يلزم إعادة تشغيل التطبيق لتطبيق تغيير اللغة بالكامل': 'Un redémarrage est nécessaire pour appliquer la langue',
  'تم تغيير لغة النظام. اضغط على زر إعادة التشغيل الآن لتطبيق التغيير وإعادة تشغيل البرنامج فوراً.': 'La langue a été modifiée. Cliquez sur Redémarrer maintenant.',
  'إعادة التشغيل الآن': 'Redémarrer maintenant',
  'لاحقاً': 'Plus tard',
  'فشل تحميل قائمة المستخدمين': 'Échec du chargement de la liste des utilisateurs',
  'الرجاء إدخال اسم المستخدم الكامل': 'Veuillez saisir le nom complet',
  'رمز PIN يجب أن يكون 4 أرقام على الأقل': 'Le PIN doit comporter au moins 4 chiffres',
  'تم إضافة': 'Ajouté',
  'بنجاح': 'avec succès',
  'فشل إضافة المستخدم': 'Échec de l\'ajout de l\'utilisateur',
  'هل أنت متأكد من رغبتك في حذف المستخدم': 'Voulez-vous vraiment supprimer cet utilisateur',
  'تم حذف المستخدم': 'Utilisateur supprimé',
  'فشل حذف المستخدم': 'Échec de la suppression',
  'تم تحديث بيانات المستخدم': 'Données utilisateur mises à jour',
  'فشل تحديث بيانات المستخدم': 'Échec de la mise à jour',
  'رمز PIN الجديد يجب أن يكون 4 أرقام على الأقل': 'Le nouveau PIN doit comporter au moins 4 chiffres',
  'رمز PIN الجديد وتأكيده غير متطابقين': 'Les codes PIN ne correspondent pas',
  'تم تغيير رمز PIN لـ': 'PIN modifié pour',
  'فشل تغيير رمز PIN': 'Échec de la modification du PIN',
  'فشل تحميل قائمة الفروع': 'Échec du chargement des succursales',
  'فشل تحميل سجل التدقيق والعمليات': 'Échec du chargement du journal d\'audit',
  'فشل تحميل الفئات': 'Échec du chargement des catégories',
  'فتح الصندوق — بداية الدوام': 'Ouverture de caisse — Début de journée',
  'يرجى إدخال مبلغ فتح الصندوق بشكل صحيح': 'Veuillez saisir un montant d\'ouverture valide',
  'تم فتح الصندوق وبداية وردية العمل بنجاح': 'Caisse ouverte avec succès',
  'فشل فتح الوردية': 'Échec de l\'ouverture de caisse',
  'مرحباً بك! قبل البدء في عمليات البيع، يرجى إدخال مبلغ السيولة النقدية المتوفرة في أدراج الصندوق (الفكة والسيولة الأولية).': 'Bienvenue ! Veuillez saisir le fond de caisse initial.',
  'فتح لاكاس': 'Ouvrir Caisse',
  'اختبار لاكاس': 'Test Caisse',
  'شاشة فوريّة': 'Écran Rapide',
  'شاشة سريعة': 'Écran Rapide',
  'ديون المورد المستحقة': 'Dettes Fournisseur Duès',
  'تسديد الدين': 'Régler la Dette',
  'خالي من الديون': 'Aucune Dette',
  'فاتورة شراء': 'Facture d\'Achat',
  'كشف الحساب': 'Relevé de Compte',
  'العنوان / الموقع': 'Adresse / Emplacement',
  'تعديل فرع': 'Modifier la Succursale',
  'غير محدد': 'Non Spécifié',
  'تعديل بيانات': 'Modifier les données',
  'إضافة فاتورة شراء': 'Nouvelle Facture d\'Achat',
  'تسديد مستحقات المورد': 'Règlement Fournisseur',
  'تأكيد حذف المنتج': 'Confirmer la suppression',
  'نعم، احذف المنتج': 'Oui, supprimer',
  'تأكيد إلغاء الفاتورة وإعادة السلع للمخزون': 'Confirmer l\'annulation de la facture',
  'حسب الوردية': 'Par session',
  'F2: تم التوجيه لبحث المنتجات والباركود': 'F2: Recherche produits & code-barres',
  'F4: تم إرسال أمر فتح درج النقود': 'F4: Commande ouverture caisse envoyée',
  'تعذر فتح درج النقود: ': 'Impossible d\'ouvrir la caisse: ',
  'تأكد من توصيل الطابعة/الدرج': 'Vérifiez la connexion imprimante/tiroir',
  'ESC: تم تفريغ السلة': 'ESC: Panier vidé',
  'آخر نسخة:': 'Dernière sauvegarde :',
  'إضافة زبون جديد فوراً': 'Ajouter un client immédiatement',
  'إغلاق المعاينة': 'Fermer l\'aperçu',
  'إغلاق النافذة والعودة': 'Fermer la fenêtre et revenir',
  'اختر الطابعة للمعاينة:': 'Choisir l\'imprimante pour l\'aperçu :',
  'اختر مجلد خارجي': 'Choisir un dossier externe',
  'اسم الزبون يجب أن يحتوي على حرفين على الأقل': 'Le nom du client doit contenir au moins 2 caractères',
  'اسم المنتج': 'Nom du produit',
  'افتراضي': 'Par défaut',
  'افتراضية': 'Par défaut',
  'البحث باسم المنتج، المقاس، اللون، أو الباركود...': 'Rechercher par nom, taille, couleur ou code-barres...',
  'الجزائر العاصمة': 'Alger',
  'الدور والصلاحية': 'Rôle et autorisations',
  'الطابعة الافتراضية للفرع': 'Imprimante par défaut de la succursale',
  'العرض:': 'Largeur :',
  'العنوان التفصيلي': 'Adresse détaillée',
  'اللغة:': 'Langue :',
  'المجلد الخارجي غير متصل!': 'Dossier externe non connecté !',
  'المسار المخصص': 'Chemin personnalisé',
  'المسار النشط حالياً:': 'Chemin actuellement actif :',
  'الوصف': 'Description',
  'بدون فئة': 'Sans catégorie',
  'بوتيك الملاح للملابس': 'Boutique Mellah Vêtements',
  'تأكيد استرجاع النسخة الاحتياطية': 'Confirmer la restauration de la sauvegarde',
  'تجربة فتح درج النقود يدويًا (ESC/POS)': 'Test d\'ouverture manuelle du tiroir-caisse (ESC/POS)',
  'تعديل المستخدم': 'Modifier l\'utilisateur',
  'تعديل المنتج': 'Modifier le produit',
  'تغير رمز PIN': 'Changer le code PIN',
  'تم الرجوع للمجلد الافتراضي': 'Retour au dossier par défaut réussi',
  'تم تغيير مجلد النسخ:': 'Dossier de sauvegarde modifié :',
  'تمت عملية استيراد': 'Processus d\'importation réussi',
  'تمت موافقة المدير بنجاح ✅': 'Approbation du manager réussie ✅',
  'تنبيه المخزون المنخفض!': 'Alerte stock bas !',
  'جاري الإلغاء...': 'Annulation en cours...',
  'جاري الاسترجاع...': 'Restauration en cours...',
  'جاري التسجيل...': 'Enregistrement en cours...',
  'جاري الحفظ...': 'Enregistrement en cours...',
  'جاري تحديث الأسعار...': 'Mise à jour des prix...',
  'جاري تحميل السجل...': 'Chargement de l\'historique...',
  'جاري...': 'En cours...',
  'جارية': 'En cours',
  'جاهز لحفظ الإعدادات في جميع التبويبات': 'Prêt à sauvegarder dans tous les onglets',
  'حاسبة التقسيم للدفع المختلط (نقداً + CIB)': 'Calculateur de paiement mixte (Espèces + CIB)',
  'حدث خطأ أثناء فحص الاتصال': 'Erreur lors de la vérification de la connexion',
  'حدد عدد الملصقات لكل مقاس ولون:': 'Définir le nombre d\'étiquettes par taille/couleur :',
  'حذف الزبون': 'Supprimer le client',
  'حفظ الزبون': 'Enregistrer le client',
  'حفظ الفرع': 'Enregistrer la succursale',
  'حفظ المنتج والمصفوفة': 'Enregistrer le produit et la matrice',
  'حفظ المورد': 'Enregistrer le fournisseur',
  'حفظ واختيار الزبون': 'Enregistrer et sélectionner le client',
  'خيارات': 'Options',
  'دج': 'DZD',
  'دج كارت': 'DZD Carte',
  'دج لـ': 'DZD pour',
  'دج مقابل': 'DZD contre',
  'دج نقد': 'DZD Espèces',
  'دج!': 'DZD !',
  'دفوعات تسديد الديون المنسوبة:': 'Paiements des dettes attribuées :',
  'دين متبقي:': 'Dette restante :',
  'ذهبي': 'Or',
  'رصيد المتجر الحالي:': 'Avoir actuel du magasin :',
  'رقم الوصل الأصلي': 'N° de reçu d\'origine',
  'رقم فاتورة المورد (اختياري)': 'N° facture fournisseur (optionnel)',
  'رمز PIN': 'Code PIN',
  'رمز PIN (4 أرقام لتسجيل الدخول)': 'Code PIN (4 chiffres pour connexion)',
  'رمز PIN الجديد': 'Nouveau code PIN',
  'رمز PIN الخاص بالمدير غير صحيح': 'Code PIN manager incorrect',
  'رمز PIN غير صحيح': 'Code PIN incorrect',
  'زبون عام': 'Client Général',
  'زبون ممتاز (VIP)': 'Client VIP',
  'زيارات': 'visites',
  'سبب إلغاء الفاتورة': 'Raison de l\'annulation',
  'سجل': 'Historique',
  'سجل الحركات': 'Historique des mouvements',
  'سجل مشتريات ودفعات الزبون': 'Historique des achats et paiements du client',
  'سجل ورديات العمل وصندوق الكاشير (Shift Audit Log)': 'Journal de clôture de caisse et de quart',
  'سروال جينز عصري': 'Jean Tendance',
  'سروال جينز عصري (تجربة)': 'Jean Tendance (Test)',
  'سعر البيع (دج)': 'Prix de vente (DZD)',
  'سعر البيع الافتراضي (DA)': 'Prix de vente par défaut (DZD)',
  'سعر التكلفة (DA) — اختياري لحساب الربح': 'Prix d\'achat (DZD) — optionnel pour calcul profit',
  'سعر التكلفة (دج)': 'Prix d\'achat (DZD)',
  'سعر خاص (اختياري)': 'Prix spécial (optionnel)',
  'سلع': 'Articles',
  'شكراً لزيارتكم، البضاعة المباعة ترجع أو تبدل خلال 7 أيام مع إحضار الفاتورة.': 'Merci de votre visite. Les marchandises sont échangeables dans les 7 jours avec ticket.',
  'صامت': 'Muet',
  'طابعة الفواتير': 'Imprimante de tickets',
  'طباعة التيكيتات لجميع الخيارات بالتسلسل': 'Imprimer les étiquettes de toutes les variantes',
  'طباعة الفاتورة': 'Imprimer le ticket',
  'طباعة باركود حقيقي': 'Imprimer vrais codes-barres',
  'طريقة الاسترداد': 'Mode de remboursement',
  'طريقة التسديد': 'Mode de paiement',
  'طريقة الدفع:': 'Mode de paiement :',
  'طلبية تزود': 'Commande de réapprovisionnement',
  'عادي': 'Normal',
  'عدد الفواتير والعمليات': 'Nombre de factures et opérations',
  'عرض التفاصيل والجرد': 'Afficher détails et inventaire',
  'عرض التفاصيل والطباعة': 'Afficher détails et impression',
  'عرض سجل المشتريات': 'Afficher l\'historique des achats',
  'عفواً تعذر إضافة المنتج': 'Désolé, impossible d\'ajouter le produit',
  'عملية بنجاح!': 'Opération réussie !',
  'عنوان المقر / المحل': 'Adresse du magasin',
  'غير مسجل': 'Non enregistré',
  'غير معروف': 'Inconnu',
  'غير موجود حالياً. يتم حفظ النسخ الاحتياطية مؤقتاً في المجلد المحلي.': 'Introuvable actuellement. Sauvegardes enregistrées localement.',
  'غير موجود في القاعدة': 'Introuvable dans la base',
  'فاتورة': 'Facture',
  'فاتورة ID:': 'ID Facture :',
  'فتح درج النقود معطّل': 'Ouverture tiroir-caisse désactivée',
  'فتح درج النقود مفعّل': 'Ouverture tiroir-caisse activée',
  'فشل إرسال الفاتورة التجريبية للطابعة': 'Échec de l\'envoi du ticket test à l\'imprimante',
  'فشل إضافة الخيار — تأكد من عدم تكرار الباركود': 'Échec de l\'ajout — vérifiez que le code-barres n\'existe pas',
  'فشل إضافة الزبون': 'Échec de l\'ajout du client',
  'فشل إضافة الفرع': 'Échec de l\'ajout de la succursale',
  'فشل إضافة المنتج': 'Échec de l\'ajout du produit',
  'فشل إضافة المورد': 'Échec de l\'ajout du fournisseur',
  'فشل التحقق من رمز المدير': 'Échec de vérification du code manager',
  'فشل التعديل الجماعي لأسعار المنتجات': 'Échec de la mise à jour groupée des prix',
  'فشل الرجوع للمجلد الافتراضي': 'Échec du retour au dossier par défaut',
  'فشل تحديث بيانات الزبون': 'Échec de la mise à jour du client',
  'فشل تحديث بيانات الفرع': 'Échec de la mise à jour de la succursale',
  'فشل تحميل التقارير': 'Échec du chargement des rapports',
  'فشل تحميل المنتجات للطباعة': 'Échec du chargement des produits pour impression',
  'فشل تحميل المنتجات للفرع الحالي': 'Échec du chargement des produits',
  'فشل تحميل تفاصيل المنتج': 'Échec du chargement des détails du produit',
  'فشل تحميل سجل المبيعات': 'Échec du chargement de l\'historique des ventes',
  'فشل تحميل سجل المرتجعات': 'Échec du chargement des retours',
  'فشل تحميل سجل حركات المخزون': 'Échec du chargement des mouvements de stock',
  'فشل تحميل سجل مشتريات وتسديدات الزبون': 'Échec du chargement des achats/paiements client',
  'فشل تحميل قائمة الزبائن والديون': 'Échec du chargement des clients et dettes',
  'فشل تحميل قائمة المنتجات والزبائن للفرع الحالي': 'Échec du chargement des produits et clients',
  'فشل تحميل قائمة الموردين': 'Échec du chargement de la liste des fournisseurs',
  'فشل تحميل كشف حساب المورد': 'Échec du chargement du relevé fournisseur',
  'فشل تسجيل تسديد المستحقات': 'Échec de l\'enregistrement du règlement',
  'فشل تسجيل عملية تسديد الدين': 'Échec de l\'enregistrement du paiement de dette',
  'فشل تسجيل فاتورة الشراء': 'Échec de l\'enregistrement de la facture d\'achat',
  'فشل تصدير بيانات المخزون': 'Échec de l\'exportation des données de stock',
  'فشل جلب تفاصيل الفاتورة': 'Échec de la récupération des détails de la facture',
  'فشل حذف الزبون': 'Échec de la suppression du client',
  'فشل حذف الفرع': 'Échec de la suppression de la succursale',
  'فشل حذف المنتج': 'Échec de la suppression du produit',
  'فشل حفظ الإعدادات': 'Échec de l\'enregistrement des paramètres',
  'فشل حفظ التعديلات': 'Échec de l\'enregistrement des modifications',
  'فشل فتح اختيار المجلد': 'Échec de l\'ouverture du sélecteur de dossier',
  'فشل فحص التحديثات': 'Échec de la vérification des mises à jour',
  'فشل فحص المنتجات ناقصة المخزون': 'Échec de la vérification du stock bas',
  'فشل:': 'Échec :',
  'فضي': 'Argent',
  'فواتير الشراء وديون السلع (Fournisseurs)': 'Achats & dettes fournisseurs',
  'فواتير المبيعات:': 'Factures de vente :',
  'قميص رجالي فاخر': 'Chemise Homme Luxe',
  'قميص رجالي فاخر (تجربة)': 'Chemise Homme Luxe (Test)',
  'قميص قطني فاخر / Chemise Coton': 'Chemise en Coton Luxe',
  'كاشير (نقطة البيع فقط)': 'Caissier (POS uniquement)',
  'كاشير التجربة': 'Caissier Test',
  'كاشير الفرع': 'Caissier du magasin',
  'كريدي': 'Crédit',
  'كشف حساب': 'Relevé de compte',
  'لا تملك فروعاً إضافية حالياً': 'Vous n\'avez pas de succursales supplémentaires',
  'لا توجد بيانات مبيعات بعد': 'Aucune donnée de vente pour le moment',
  'لا توجد بيانات ورديات للتصدير حالياً': 'Aucune donnée de quart à exporter',
  'لا توجد حركات مسجلة في سجل التدقيق تطابق البحث': 'Aucun mouvement d\'audit ne correspond',
  'لا توجد عمليات إرجاع مسجلة حالياً': 'Aucun retour enregistré actuellement',
  'لا توجد عمليات مبيعات سابقة لهذا الزبون.': 'Aucune vente précédente pour ce client.',
  'لا توجد منتجات مسجلة تطابق البحث': 'Aucun produit ne correspond à la recherche',
  'لا توجد ورديات سابقة': 'Aucun quart précédent',
  'لا توجد وردية مفتوحة لإتمام البيع': 'Aucune caisse ouverte pour valider la vente',
  'لا يمكن حذف الفرع الأخير للنظام': 'Impossible de supprimer la dernière succursale',
  'لا يوجد زبائن مسجلين يطابقون البحث': 'Aucun client ne correspond à la recherche',
  'لا يوجد مخزون للتصدير حالياً': 'Aucun stock à exporter actuellement',
  'لا يوجد مستخدمين حالياً': 'Aucun utilisateur actuellement',
  'لا يوجد موردين مسجلين يطابقون البحث': 'Aucun fournisseur ne correspond à la recherche',
  'مبلغ الفتح': 'Montant d\'ouverture',
  'متطابق': 'Conforme',
  'مثال: 0550123456': 'Ex: 0550123456',
  'مثال: 0661234567': 'Ex: 0661234567',
  'مثال: 5555': 'Ex: 5555',
  'مثال: XL': 'Ex: XL',
  'مثال: أسود': 'Ex: Noir',
  'مثال: الجزائر العاصمة، حي حسيبة بن بوعلي': 'Ex: Alger, Hassiba Ben Bouali',
  'مثال: خطأ في الصرف / طلب الزبون': 'Ex: Erreur de monnaie / Demande client',
  'مثال: دفعة جزئية عن مشتريات الأسبوع': 'Ex: Acompte sur les achats de la semaine',
  'مثال: شارع العربي بن مهيدي، وهران': 'Ex: Rue Larbi Ben M\'hidi, Oran',
  'مثال: فرع وهران — حي السلام': 'Ex: Succursale Oran — Hai Salam',
  'مثال: كريم حماني': 'Ex: Karim Hamani',
  'مثال: ياسمين بن علي': 'Ex: Yasmine Ben Ali',
  'مثلاً: 10 أو -500': 'Ex: 10 ou -500',
  'مثلاً: 5000': 'Ex: 5000',
  'مثلاً: محمد الأمين': 'Ex: Mohamed Amine',
  'مجلد النسخ الاحتياطي التلقائي': 'Dossier de sauvegarde automatique',
  'مدير': 'Manager',
  'مدير (صلاحيات كاملة)': 'Directeur (Accès complet)',
  'مدير نظام': 'Admin système',
  'مرحباً بك يا': 'Bienvenue',
  'مستخدم آخر': 'Autre utilisateur',
  'مسح C': 'Effacer C',
  'مشرف': 'Superviseur',
  'مشرف (مبيعات + مخزون + تقارير)': 'Superviseur (Ventes + Stock + Rapports)',
  'مشرف فرع': 'Superviseur succursale',
  'مشفر Bcrypt': 'Crypté Bcrypt',
  'معاينة شكل الفاتورة الحرارية (Live Thermal Receipt Preview)': 'Aperçu du ticket thermique',
  'معاينة ملصق الباركود (Live Barcode Sticker Preview)': 'Aperçu de l\'étiquette code-barres',
  'مفتوحة': 'Ouverte',
  'مفعل': 'Activé',
  'مقارنة وسائل الدفع': 'Comparaison des modes de paiement',
  'مقاس عادي': 'Taille standard',
  'ملاحظات التسديد': 'Notes de paiement',
  'ملاحظات التسديد (اختياري)': 'Notes de paiement (optionnel)',
  'ملاحظات الشراء': 'Notes d\'achat',
  'ملاحظات المورد': 'Notes du fournisseur',
  'ملاحظة': 'Note',
  'ممتاز! لا توجد أي سلع منخفضة المخزون حالياً': 'Parfait ! Aucun article en stock bas actuellement',
  'منتج بنجاح من ملف CSV!': 'Produits importés du fichier CSV avec succès !',
  'نسخة محفوظة': 'sauvegarde(s) enregistrée(s)',
  'نشطة': 'Active',
  'نفد (0)': 'Épuisé (0)',
  'نقد': 'Espèces',
  'نقداً (Cash)': 'Espèces (Cash)',
  'نقطة': 'pt',
  'نقطة ولاء': 'points de fidélité',
  'هل أنت متأكد من رغبتك في حذف الزبون': 'Voulez-vous vraiment supprimer le client',
  'هل أنت متأكد من رغبتك في حذف الفرع': 'Voulez-vous vraiment supprimer la succursale',
  'هل تريد تسجيل الخروج؟': 'Voulez-vous vous déconnecter ?',
  'وحدة': 'unité',
  'وصف مختصر للمنتج': 'Brève description du produit',
  'يترك فارغ = سعر المنتج': 'Laisser vide = Prix par défaut du produit',
  'يتيح لك هذا الخيار زيادة أو تخفيض أسعار المنتجات دفعة واحدة لجميع المنتجات أو حسب فئة معينة.': 'Permet de modifier les prix en masse pour tous les produits ou par catégorie.',
  'يرجى إدخال سعر بيع صحيح أكبر من 0': 'Veuillez saisir un prix de vente valide supérieur à 0',
  'يرجى إدخال قيمة التعديل (أكبر أو أقل من 0)': 'Veuillez saisir la valeur d\'ajustement',
  'يرجى إضافة خيار واحد على الأقل': 'Veuillez ajouter au moins une option',
  'يرجى تحديد عدد التيكيتات المراد طباعتها (أكبر من 0)': 'Veuillez spécifier le nombre d\'étiquettes à imprimer',
  'يرجى كتابة إجمالي مبلغ الفاتورة': 'Veuillez saisir le montant total de la facture',
  'يرجى كتابة اسم الزبون': 'Veuillez saisir le nom du client',
  'يرجى كتابة اسم الفرع': 'Veuillez saisir le nom de la succursale',
  'يرجى كتابة اسم المنتج': 'Veuillez saisir le nom du produit',
  'يرجى كتابة اسم المورد': 'Veuillez saisir le nom du fournisseur',
  'يرجى كتابة مبلغ التسديد الصحيح': 'Veuillez saisir un montant de paiement correct',
  'يرجى كتابة مبلغ تسديد صحيح': 'Veuillez saisir un montant de paiement valide',
  '🏷️ التعديل الجماعي لأسعار البيع (Bulk Price Update)': '🏷️ Mise à jour groupée des prix de vente',
  '💳 بطاقة CIB / الذهبية': '💳 Carte CIB / Edahabia',
  '💵 نقداً (Cash)': '💵 Espèces (Cash)',
  '📋 اقتراح طلبية التزود الشاملة للموردين (Auto Purchase Order)': '📋 Suggestion de bon de commande automatique',
  '🧾 جاري ترحيل الفاتورة للطابعة...': '🧾 Impression du ticket en cours...',

  'Bleu/أزرق': 'Bleu/Bleu',
  'Jean Dupont / محمد العماري': 'Jean Dupont / Mohamed El Amari',
  'Noir/أسود': 'Noir/Noir',
  'أحمد المدير': 'Ahmed Directeur',
  'أدخل اسم المنتج': 'Entrez le nom du produit',
  'أدخل رمز PIN أولاً': 'Entrez le code PIN d\'abord',
  'أدخل رمز PIN الخاص بك': 'Entrez votre code PIN',
  'أدخل مبلغ بداية اليوم': 'Entrez le montant de début de journée',
  'أدخل وصفاً قصيراً للمنتج...': 'Entrez une brève description du produit...',
  'إجمالي الحركات المسجلة:': 'Total des mouvements enregistrés :',
  'إجمالي الدين المستحق حالياً:': 'Total de la dette actuelle :',
  'إجمالي الشراء:': 'Total des achats :',
  'إجمالي العوائد': 'Total des retours',
  'إجمالي المخزون': 'Total du stock',
  'إجمالي المستحقات المتبقية للمورد:': 'Total dû au fournisseur :',
  'إجمالي المشتريات التراكمي': 'Cumul total des achats',
  'إجمالي المنتجات المطلوب إعادة تزودها:': 'Total des produits à réapprovisionner :',
  'إجمالي مبلغ السلعة المشتراة (دج)': 'Montant total de l\'article acheté (DZD)',
  'إدارة الموردين والديون': 'Gestion des fournisseurs et dettes',
  'إضافة زبون جديد للمتجر': 'Ajouter un nouveau client au magasin',
  'إضافة منتج جديد وتوليد الخيارات': 'Ajouter un produit et générer les déclinaisons',
  'إضافة مورد جديد': 'Ajouter un nouveau fournisseur',
  'إضافة مورد سلع جديد': 'Ajouter un fournisseur d\'articles',
  'إعادة الاتصال بالشبكة والمزامنة يدوياً': 'Reconnexion et synchronisation manuelle',
  'إغلاق': 'Fermer',
  'إلى': 'À',
  'ابحث باسم الزبون أو رقم الهاتف...': 'Rechercher par nom de client ou téléphone...',
  'ابحث باسم المنتج، اللون، المقاس، أو امسح الباركود... (F2)': 'Rechercher par produit, couleur, taille ou scan (F2)',
  'ابحث باسم المورد، اسم الشركة، أو رقم الهاتف...': 'Rechercher par fournisseur, société ou téléphone...',
  'اختر السلع من القائمة أو امسح الباركود للبدء': 'Sélectionnez les articles ou scannez le code-barres',
  'اختر حسابك لتسجيل الدخول': 'Choisissez votre compte pour vous connecter',
  'اختر زبون لجمع نقاط الولاء': 'Choisir un client pour cumuler des points',
  'اختياري': 'Optionnel',
  'اسم الزبون الكامل': 'Nom complet du client',
  'اسم الزبون والتصنيف': 'Nom du client et catégorie',
  'اسم الشركة / العلامة (اختياري)': 'Nom de la société / Marque (optionnel)',
  'اسم المنتج (مثال: تي شيرت كلاسيك)': 'Nom du produit (Ex: T-Shirt Classique)',
  'اسم المنتج يجب أن يحتوي على حرفين على الأقل': 'Le nom du produit doit contenir au moins 2 caractères',
  'اسم المورد أو الوكيل': 'Nom du fournisseur ou agent',
  'اسم المورد والشركة': 'Nom du fournisseur et société',
  'التاريخ': 'Date',
  'الجزائر العاصمة، حي حسيبة بن بوعلي': 'Alger, Rue Hassiba Ben Bouali',
  'الحد الأدنى': 'Seuil minimum',
  'الخيار': 'Option',
  'الدخول برمز PIN مباشرة بدون اختيار حساب': 'Connexion directe par code PIN sans sélection',
  'الدين المستحق الحالي': 'Dette actuelle due',
  'الديون المستحقة': 'Dettes dues',
  'الرمزان غير متطابقين': 'Les deux codes PIN ne correspondent pas',
  'الزبون:': 'Client :',
  'السبب:': 'Raison :',
  'السعر الخاص': 'Prix spécial',
  'السعر يجب أن يكون مبلغاً موجباً أكبر من 0': 'Le prix doit être supérieur à 0',
  'السلة فارغة، أضف منتجات أولاً': 'Panier vide, ajoutez d\'abord des produits',
  'السلة فارغة، لا يمكن تعليقها': 'Panier vide, impossible de le mettre en attente',
  'السلع والخيارات التالية اقتربت من النفاد أو نفدت بالكامل. قمنا بحساب الكمية المقترحة للشراء تلقائياً للوصول للمستوى الآمن (10 قطع لكل خيار).': 'Stock critique. Quantités suggérées calculées automatiquement.',
  'الطباعة التلقائية معطّلة': 'Impression automatique désactivée',
  'الطباعة التلقائية مفعّلة': 'Impression automatique activée',
  'العد الفعلي': 'Comptage réel',
  'العودة': 'Retour',
  'العودة لقائمة المنتجات': 'Retour à la liste des produits',
  'الفئة': 'Catégorie',
  'الفرق (عجز/فائض)': 'Écart (déficit/excédent)',
  'الكاشير:': 'Caissier :',
  'الكمية': 'Quantité',
  'الكمية المباعة': 'Quantité vendue',
  'الكمية المرجوعة': 'Quantité retournée',
  'المبلغ': 'Montant',
  'المبلغ الأولي في الصندوق (DA)': 'Montant d\'ouverture du fonds de caisse (DZD)',
  'المبلغ المتبقي كدين للمورد (Dette):': 'Solde dû au fournisseur (Dette) :',
  'المبلغ المدفوع تسقيع / نقداً للمورد (دج)': 'Montant versé au fournisseur (DZD)',
  'المبلغ المسترد': 'Montant remboursé',
  'المبلغ المسدد (دج)': 'Montant réglé (DZD)',
  'المبيعات': 'Ventes',
  'المحسوب متوقع': 'Calculé attendu',
  'المخزون الحالي (Ledger)': 'Stock actuel (Registre)',
  'المظهر والصوت': 'Apparence et son',
  'المعلومات الأساسية للمنتج': 'Informations de base du produit',
  'المقترح للشراء': 'Quantité suggérée',
  'المنتج الخيار': 'Produit et option',
  'المنتج المرجوع': 'Produit retourné',
  'المنتج غير موجود في الفرع الحالي': 'Produit introuvable dans cette succursale',
  'المنتج والخيار': 'Produit et déclinaison',
  'الموردين والديون': 'Fournisseurs et Dettes',
  'النسخ الاحتياطي': 'Sauvegardes',
  'النظام': 'Système',
  'النظام الآلي': 'Système automatique',
  'النوع': 'Type',
  'الوصف (اختياري)': 'Description (optionnel)',
  'بدون باركود': 'Sans code-barres',
  'بدون سبب مذكور': 'Sans motif indiqué',
  'بدون لون': 'Sans couleur',
  'بدون مقاس': 'Sans taille',
  'بطاقة': 'Carte',
  'بطاقة CIB / الذهبية': 'Carte CIB / Edahabia',
  'بمبلغ': 'D\'un montant de',
  'بنطلون جينز / Jean Classic': 'Pantalon Jean Classique',
  'بواسطة': 'Par',
  'بيانات المتجر': 'Informations du magasin',
  'تأكد من اختيار الفئة أو كلمة البحث بشكل صحيح': 'Vérifiez la catégorie ou le mot-clé',
  'تأكيد الإلغاء وإعادة السلع': 'Confirmer l\'annulation et le retour',
  'تأكيد الاسترجاع والبدء': 'Confirmer et démarrer la restauration',
  'تأكيد رمز PIN الجديد': 'Confirmer le nouveau code PIN',
  'تأكيد وحفظ تسديد الدين': 'Confirmer et enregistrer le règlement',
  'تأكيد وحفظ تسديد المستحقات': 'Confirmer et enregistrer le paiement dû',
  'تأكيد وفتح الصندوق': 'Confirmer et ouvrir la caisse',
  'تاريخ الإنشاء': 'Date de création',
  'تاريخ البيع:': 'Date de vente :',
  'تاريخ الفتح والإغلاق': 'Dates d\'ouverture et de clôture',
  'تجربة الطابعة': 'Test d\'impression',
  'تحقق من وجود إصدارات أحدث من Mellah POS.': 'Vérifier les nouvelles versions de Mellah POS.',
  'تسجيل الدخول': 'Connexion',
  'تسجيل فاتورة الشراء وتحديث الدين': 'Enregistrer achat et mettre à jour dette',
  'تسجيل مرتجع جديد': 'Enregistrer un nouveau retour',
  'تسديد دين الزبون': 'Régler la dette du client',
  'تسديد مبلغ:': 'Règlement d\'un montant de :',
  'تصدير الطلبية لـ Excel (CSV)': 'Exporter la commande vers Excel (CSV)',
  'تصدير الورديات CSV': 'Exporter les quarts en CSV',
  'تعديل الزبون': 'Modifier le client',
  'تعديل المخزون': 'Ajuster le stock',
  'تعذر الاتصال بالشبكة، تحقق من اتصال الإنترنت (أوفلاين)': 'Connexion réseau impossible (Hors ligne)',
  'تعذرت الطباعة — تحقق من اتصال الطابعة': 'Impression impossible — vérifiez l\'imprimante',
  'تعذرت الطباعة — تحقق من اتصال الطابعة (يمكنك إعادة الطباعة من سجل المبيعات)': 'Impression impossible — vérifiez l\'imprimante (réimprimable depuis l\'historique)',
  'تغيير PIN': 'Changer le PIN',
  'تفريغ السلة': 'Vider le panier',
  'تم أرشفة الفرع': 'Succursale archivée avec succès',
  'تم إرسال أمر الطباعة التجريبية! 🖨️': 'Ordre d\'impression test envoyé ! 🖨️',
  'تم إرسال أمر الطباعة الحرارية بنجاح 🖨️': 'Ordre d\'impression thermique envoyé 🖨️',
  'تم إرسال أمر فتح درج النقود بنجاح! 💵': 'Ordre d\'ouverture du tiroir-caisse envoyé ! 💵',
  'تم إضافة الزبون بنجاح!': 'Client ajouté avec succès !',
  'تم إضافة الفرع بنجاح!': 'Succursale ajoutée avec succès !',
  'تم إضافة المنتج وجميع الخيارات والمخزون بنجاح!': 'Produit et déclinaisons ajoutés avec succès !',
  'تم إضافة المورد بنجاح!': 'Fournisseur ajouté avec succès !',
  'تم إضافة خيار جديد للمنتج': 'Nouvelle déclinaison ajoutée au produit',
  'تم إيقاف الطباعة التلقائية (يمكنك الطباعة يدوياً عند الحاجة)': 'Impression automatique désactivée',
  'تم إيقاف فتح الدرج التلقائي (يمكن الفتح يدوياً)': 'Ouverture automatique du tiroir désactivée',
  'تم استرجاع السلة المعلقة بنجاح! 🛒': 'Panier en attente récupéré ! 🛒',
  'تم الاتصال بالشبكة بنجاح (أونلاين)': 'Connexion réseau établie (En ligne)',
  'تم الاتصال ومزامنة': 'Connecté et synchronisé',
  'تم تحديث أسعار المنتجات المحددة بنجاح!': 'Prix mis à jour avec succès !',
  'تم تحديث بيانات الزبون': 'Données du client mises à jour',
  'تم تحديث بيانات الفرع': 'Données de la succursale mises à jour',
  'تم تحديث بيانات المنتج بنجاح': 'Données du produit mises à jour',
  'تم تسجيل تسديد مستحقات المورد': 'Paiement fournisseur enregistré',
  'تم تسجيل فاتورة الشراء وتحديث ديون المورد': 'Facture d\'achat et dettes mises à jour',
  'تم تسديد مبلغ': 'Paiement effectué de',
  'تم تصدير النسخة الاحتياطية بنجاح:': 'Sauvegarde exportée avec succès :',
  'تم تصدير تقرير المخزون لملف CSV بنجاح!': 'Rapport de stock exporté en CSV !',
  'تم تصدير تقرير الورديات إلى ملف CSV بنجاح!': 'Rapport des quarts exporté en CSV !',
  'تم تصدير قائمة التزود لملف CSV بنجاح للمورد!': 'Bon de commande exporté en CSV !',
  'تم تطبيق خصم من رصيد المتجر:': 'Remise avoir magasin appliquée :',
  'تم تعليق السلة الحالية بنجاح (F2) ⏸️': 'Panier mis en attente (F2) ⏸️',
  'تم تفعيل الطباعة التلقائية للفواتير': 'Impression automatique activée',
  'تم تفعيل فتح درج النقود تلقائياً بعد البيع': 'Ouverture automatique du tiroir activée',
  'تم حذف الزبون': 'Client supprimé',
  'تم حذف المنتج': 'Produit supprimé',
  'تم حفظ إعدادات المتجر وطابعة الفواتير واللغة بنجاح! ✅': 'Paramètres enregistrés avec succès ! ✅',
  'تم حفظ تقسيم الدفع المختلط بنجاح!': 'Paiement mixte enregistré !',
  'تم خصم': 'Déduit',
  'تم فتح الدرج (أو إرسال التنبيه المحلي للطابعة)': 'Tiroir-caisse ouvert',
  'تمت استعادة البيانات بنجاح! الإجمالي:': 'Restauration réussie ! Total :',

}

export interface LanguageState {
  language: Language
  version: number
  setLanguage: (lang: Language) => void
  t: (keyOrText: string) => string
}

const initialLang = (localStorage.getItem('mellah_lang') as Language) || 'ar'
if (typeof document !== 'undefined') {
  document.documentElement.dir = initialLang === 'ar' ? 'rtl' : 'ltr'
  document.documentElement.lang = initialLang
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: initialLang,
  version: 0,

  setLanguage: (language: Language) => {
    localStorage.setItem('mellah_lang', language)
    if (typeof document !== 'undefined') {
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = language
    }
    set({ language, version: get().version + 1 })
  },

  t: (keyOrText: string) => {
    const lang = get().language
    if (lang === 'ar') return keyOrText
    if (!keyOrText) return ''
    const trimmed = keyOrText.trim()
    if (frDictionary[trimmed]) return frDictionary[trimmed]
    if (frDictionary[keyOrText]) return frDictionary[keyOrText]

    // Smart regex pattern fallbacks for dynamic strings
    if (/^\d+\s*قطعة/.test(trimmed)) {
      return trimmed.replace('قطعة', 'pièce(s)')
    }
    if (trimmed.startsWith('مقاس:')) {
      return trimmed.replace('مقاس:', 'Taille:')
    }
    if (trimmed.startsWith('لون:')) {
      const colorVal = trimmed.replace('لون:', '').trim()
      const translatedColor = frDictionary[colorVal] || colorVal
      return `Couleur: ${translatedColor}`
    }
    if (trimmed.startsWith('مبيعات اليوم')) {
      return trimmed.replace('مبيعات اليوم', 'Ventes du Jour').replace('عملية', 'opérations')
    }
    if (trimmed.startsWith('جميع الفئات')) {
      return trimmed.replace('جميع الفئات', 'Toutes les Catégories')
    }
    if (/^\d+\s*فاتورة/.test(trimmed)) {
      return trimmed.replace('فاتورة', 'facture(s)').replace('فواتير', 'factures')
    }

    return keyOrText
  },
}))
